# Generated by Django 4.1.7 on 2023-03-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_comments_posts"),
    ]

    operations = [
        migrations.RenameModel(old_name="Comments", new_name="Comment",),
        migrations.RenameModel(old_name="Posts", new_name="Post",),
    ]
