# Generated by Django 4.1.7 on 2023-03-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_rename_comments_comment_rename_posts_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
