# Generated by Django 4.1.7 on 2023-03-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_alter_post_datetime"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="comment_id",),
    ]
