# Generated by Django 4.1.7 on 2023-03-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_follower"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follower", unique_together={("user", "follower")},
        ),
    ]
